### PR TITLE
Imagery for the top

### PR DESCRIPTION
**Pull request by rgbkrk**
It's nice to have an image at the top of the README, IMO. This one is an umbrella in a lock box. :tongue:

who put this umbrella here

I did some flickr digging for Creative Commons images, wasn't sure what to pick.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Maybe this is more apt.

5400024841_ab6816606a_z

**Comment by rgbkrk** [comment]
2915859538_dcc362181f_z

**Comment by rgbkrk** [comment]
3214480226_a69b907899_z

**Comment by rgbkrk** [comment]
3961224223_dbaf61b51d_z

**Comment by rgbkrk** [comment]
ramkey

**Comment by rgbkrk** [comment]
ramkey768

**Comment by smashwilson** [comment]
Aww, you didn't use the Lego one? :stuck_out_tongue_winking_eye:

**Comment by rgbkrk** [comment]
Was that your favorite then?

**Comment by smashwilson** [comment]
Haha. The one you picked is just fine.

**Pull request merged**
